
// #include<ulib.h>
// // Dont try to add any other header files.
// int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
// {
//    int a = 10, b = 20;
//    printf("%d\n", a+b);
   
//    int pid = getpid();
//    printf("Pid %d\n", pid);
   
//    pid = fork();
//    if(pid == 0)
//    {
//       printf(" OS C330 Child1\n");
//       exit(0);
//    }
//    return 0;
// }
#include<ulib.h>


int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
{
    int pid;
    char buf1[4097];
    char *filename="test.txt";
    int create_fd = open(filename, O_CREAT|O_RDWR, O_READ|O_WRITE);
    // char *buf = "Hello, I am file!";
    char *buf = "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH";
     
    printf("%d\n", write(create_fd, buf, 4095));
    int read_fd = open(filename, O_RDONLY);
    printf("%d\n", read(read_fd, buf1, 4096));
    printf("%d\n", write(create_fd, buf, 1));
    printf("%d\n", write(create_fd, buf, 1));
    printf("%d\n", read(read_fd, buf1, 4096));
    // buf1[4096] = '\0';
    // printf("%s\n",buf1);
    // close(read_fd);
    // close(create_fd);
    return 0;
}
// #include<ulib.h>


// int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
// {
//   int pid;
//   char buf1[20];
//   int pipes[2];
//   int temp = pipe(pipes);
//   if(temp == -1)
//   {
//     return 0;
//   }
//   // printf("%d\n",temp);
//   pid = fork();
  
//   if(pid == 0){
//      char *buf = "Hello, I am filesssssss!";
//      close(pipes[0]);
//      // printf("close1:%d\n",close(pipes[0]));
//      printf("C:%d\n", write(pipes[1], buf, 24));
//      printf("C1:%d\n", write(pipes[1], buf, 24));

//      // Below printf will be printing -1, Because read fd is closed already
//      printf("C:%d\n", read(pipes[0], buf1, 5));
//      exit(0);
//   }else{
//      sleep(5);
//      close(pipes[1]);
//      // printf("close2:%d\n",close(pipes[1]));
     
//      printf("P:%d\n", read(pipes[0], buf1, 20));

//     // Below printf will be printing -1, Because write fd is closed already
//      printf("P:%d\n", write(pipes[1], buf1, 10));
//      buf1[20] = 0;
//      printf("P:%s\n", buf1);
//      buf1[0] = 0;
//      printf("P2:%d\n", read(pipes[0], buf1, 20));
//      printf("P3:%s\n", buf1);
//      close(pipes[0]);
//   }
// }
// #include<ulib.h>
// int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
// {
//     int pid;
//     char buf1[20];
//     char *file1="test.txt";
//     char *file2="test2.txt";

//     char *buf = "Hello, I am file!";
//     int fd_1 = open(file1, O_CREAT, O_READ|O_WRITE);
//     printf("%d\n",get_stats());
    
//     int fd_2 = open(file1, O_RDONLY); 
//     printf("%d\n",get_stats());
    
//     int fd_3 = open(file2, O_CREAT, O_READ|O_WRITE);
//     printf("%d\n",get_stats()); 
    
//     // This will not create any file descriptor as the file with the name "test2.txt" was created already.
//     int fd_4 = open(file2, O_CREAT, O_READ|O_WRITE);
//     printf("%d\n",get_stats()); 



//     close(fd_1);
//     printf("%d\n",get_stats()); 
//     close(fd_2);
//     printf("%d\n",get_stats()); 
//     close(fd_3);
//     //Below printf will be printing 3 because of Standard file descriptor(STDIN, STDOUT, STDERROR)
//     printf("%d\n",get_stats());
//     return 0;
// }
// #include<ulib.h>


// int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
// {
//     int pid;
//     char buf1[20];
//     char *filename="test.txt";
//     int create_fd = open(filename, O_CREAT|O_WRITE|O_READ, O_READ|O_WRITE);
//     char *buf = "Hello, I am filefdsffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff!";
//     write(create_fd, buf, 35);

//     int fd, dupfd;
//    char buf2[32];
//    fd = open("test.txt", O_RDONLY);
//    printf("fd = %d\n", fd);
//    printf("close_fd = %d\n", close(fd));
//     dupfd = dup2(fd, 10);
//     printf("dupfd = %d\n", dupfd);
//     return 0;
// }

// #include<ulib.h>


// int main(u64 arg1, u64 arg2, u64 arg3, u64 arg4, u64 arg5)
// {
//     int pid;
//     char buf1[20];
//     char *filename="test.txt";
//     int create_fd = open(filename, O_CREAT | O_READ | O_WRITE, O_READ|O_WRITE);
//     char *buf = "Hello, I am file!";
//     printf("%d\n", write(create_fd, buf, 17));

//     int read_fd = open(filename, O_RDONLY);
//     printf("%d\n", read(read_fd, buf1, 170));
//     buf1[17] = '\0';
//     printf("%s\n",buf1);
//     close(read_fd);
//     close(create_fd);
//     return 0;
// }